version: "3"

volumes:
  sqldata:
    driver: local
    external: false

networks:
  internal:
    external: false

services:
  postgres:
    image: postgres:latest
    container_name: "p2test_postgres"
    environment:
      - "POSTGRES_DB=edge_db"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    volumes:
      - "sqldata:/var/lib/postgresql/data"
    networks:
      - "internal"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: "p2test_pgadmin"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user@leet.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
      - "PGADMIN_DISABLE_POSTFIX=1"
    ports:
      - "5050:80"
    volumes:
      - "./pgadmin4_config/servers.json:/pgadmin4/servers.json"
    networks:
      - "internal"
    depends_on:
      - "postgres"
